name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    
#    - name: configure
#      run: ./configure
#      
#    - name: Install dependencies
#      run: make
      
    - name: Run tests
      run: make test
      
#    - name: Run distcheck
#      run: make distcheck
